[package]
name = "easyvst"
version = "0.1.0"
authors = ["Boscop"]
edition = "2018"

[dependencies]
log = "0.3"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["minwindef", "errhandlingapi", "libloaderapi"] }
